import type { Metadata } from "next";
import { Abel } from "next/font/google";
import "./globals.css";

const abel = Abel({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={abel.className}>
        <main className="flex items-center justify-center p-4">
          <div className="max-w-7xl w-full text-white">{children}</div>
        </main>
      </body>
    </html>
  );
}
